

GET http://localhost:3000/api/category/findLastCategoriesWithProducts HTTP/1.1
# GET http://localhost:3000/api/product/findByAdminWithStock
# Content-Type: application/json

# {
#   "page": 1,
#   "pageSize": 5
# }


# GET http://localhost:3000/api/product/findOneWithStock/ahhhhhhhhhhhhhhh



# GET http://localhost:3000/api/brand/findAll
# GET http://localhost:3000/api/brand/findAllEnabled


