##
# GET http://localhost:3000/api/product/findByAdminWithStock
# Content-Type: application/json

# {
#   "page": 5,
#   "pageSize": 5
# }

# aqui otro
# GET http://localhost:3000/api/product/ahhhhhhhhhhhhhhh



GET http://localhost:3000/api/brand/findAll
